### ISSUE TITLE
When i try  to get GS splat .ply file, "blendernerf_vertex_colors_tmp" not found' 

### ISSUE THREAD

**Issue by SamChonCLO** [maximeraafat/BlenderNeRF#42]
Hi I had tried to get nerf type rendered dataset and also. .ply (splats) file 

blender version : 4.3.0 4.2.3 both one
scripts : latest

`

Python: Traceback (most recent call last):
  File "C:\Users\ML-SERVER\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\BlenderNeRF\sof_operator.py", line 36, in execute
    if scene.splats: self.save_splats_ply(scene, output_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ML-SERVER\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\BlenderNeRF\blender_nerf_operator.py", line 148, in save_splats_ply
    obj.data.vertex_colors.remove(obj.data.vertex_colors[TMP_VERTEX_COLORS])
                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "blendernerf_vertex_colors_tmp" not found'

what is a 'blendernerf_vertex_colors_tmp' and how can i get this map?

**Comment by maximeraafat** [comment]
Hi @SamChonCLO, thanks for bringing up this issue.

The `blendernerf_vertex_colors_tmp` is a temporary vertex colours object created for each mesh when no vertex colours are available. After saving the `points3d.ply` file, this temporary object is deleted. However, the current implementation does not check if the `blendernerf_vertex_colors_tmp` object exists before attempting to delete it. This can cause issues if vertex colours already exist for a mesh, as the temporary object won't be created. Could you please confirm that one of your objects already has vertex colours?

I will fix this issue soon!

**Comment by maximeraafat** [comment]
Hi @SamChonCLO, sorry for the long delay. The issue should be fixed now, please let me know if you run into any further issues or if this bug persists :)

**Comment by JianxiangL** [comment]
Hello, when using it, the Gaussian points still don't have the 'color' attribute, causing 3DGS to report an error when loading the PLY point cloud.
Blender version is 4.3.1
show the .ply using the open3d visualization
![Image](https://github.com/user-attachments/assets/11cc6f53-56f8-4d13-bd45-adfe084cd6e5)

and the code report an error
![Image](https://github.com/user-attachments/assets/5ddabf38-a8f4-4b0b-a2d1-9d66e571ac98)

**Comment by JianxiangL** [comment]
> 嗨，很抱歉耽搁了这么久。该问题现在应该已修复，如果您遇到任何其他问题或此错误仍然存在，请告诉我:)

Hello, I’ve identified the issue. It’s because the objects in my scene are instanced collections, but the code only operates on meshes, missing the handling of collection instances. Although I’ve pinpointed the problem, I’m not very familiar with Blender, so I’d greatly appreciate your assistance!

**Comment by JianxiangL** [comment]
> Hi [@SamChonCLO](https://github.com/SamChonCLO), sorry for the long delay. The issue should be fixed now, please let me know if you run into any further issues or if this bug persists :)

Hello, I’ve identified the issue. It’s because the objects in my scene are instanced collections, but the code only operates on meshes, missing the handling of collection instances. Although I’ve pinpointed the problem, I’m not very familiar with Blender, so I’d greatly appreciate your assistance!

**Comment by maximeraafat** [comment]
Hi @SamChonCLO, apologies for the delay and thanks for your understanding.

Yes, I’m aware of the issue you’ve raised. At the moment, my focus is on other priorities, so I haven’t had the chance to revisit **BlenderNeRF** in detail yet. While I do hope to address the outstanding issues in `BlenderNeRF v7` at some point, I currently have limited visibility on when that might be.

In the meantime, since the project is open source, feel free to adapt or extend the plugin as needed via a fork or clone of the repository. I appreciate your patience :)
