### ISSUE TITLE
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object

### ISSUE THREAD

**Issue by HaoqinHong** [maximeraafat/BlenderNeRF#43]
Thanks for your sharing, but Sorry， I Just face  this errors when i run COS:
`Python: Traceback (most recent call last):
  File "C:\Users\Phoen\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\BlenderNeRF\cos_operator.py", line 40, in execute
    if scene.splats: self.save_splats_ply(scene, output_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Phoen\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\BlenderNeRF\blender_nerf_operator.py", line 130, in save_splats_ply
    bpy.ops.object.mode_set(mode='OBJECT')
  File "D:\blender\blender-4.3.0-windows-x64\4.3\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object
`
Do you know how to slove it? with best wishes!

**Comment by maximeraafat** [comment]
Hi @HaoqinHong, thanks for reporting this issue. While I’m not entirely sure of the exact circumstances causing this error, I’ve added a fallback check to handle cases where there is no active object. This should help prevent the issue from occurring. Feel free to try the updated code and let me know if the problem persists, thanks! :)

**Comment by HaoqinHong** [comment]
Thanks for your greate work, i wish you all the best my bro!!!!
